// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asgioodavhicalqqxjdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZ2lvb2RhdmhpY2FscXF4amRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1OTU1MTksImV4cCI6MjA3NjE3MTUxOX0.lEGr_A2R65ko_q_GUjQb0YKM0fQFUMT40TaXAcirgDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});